### ISSUE TITLE
Feature request: `private_preshared_keys` added to `WLAN`

### ISSUE THREAD

**Issue by omBratteng** [paultyng/go-unifi#212]
It would be nice if the keys `private_preshared_keys` and `private_preshared_keys_enabled` were added to the SDK.

`private_preshared_keys_enabled` is a `boolean`

and `private_preshared_keys` expects data in this format
```json
[
  {
    "networkconf_id": "Same ID as NetworkID",
    "password": "A PPSK password"
  },
  {
    "networkconf_id": "Same ID as NetworkID",
    "password": "And another PPSK password"
  }
]
```

[However this requires at least UniFi v7.5.187](https://www.hostifi.com/blog/ubiquiti-releases-unifi-7-5-187-with-support-for-ppsk)

**Comment by omBratteng** [comment]
You can also let the `networkconf_id` be different on each as well. Example if you have multiple networks, and want a different PPSK per network.

**Comment by joshuaspence** [comment]
Done in #156
