### ISSUE TITLE
Maintained?

### ISSUE THREAD

**Issue by scottd018** [paultyng/go-unifi#213]
I find this SDK as well as the Terraform provider (https://registry.terraform.io/providers/paultyng/unifi/latest/docs/resources/dynamic_dns) incredibly useful.  However, I see that it hasn't been updated in 7 months with minimal responses from the maintainer.  Is this intended to be maintained further?  If not, I am happy to fork the project and maintain on my own.  Looking for another side project for my home lab and need to extend the functionality.

EDIT: totally understand if there is no commitment to maintain.  We all get under time crunches and don't have time to keep going on some of this stuff.  Was curious, as I can submit PRs as needed to extend if this will be further maintained. :)

**Comment by joshuaspence** [comment]
Let's consolidate this discussion here: https://github.com/paultyng/terraform-provider-unifi/issues/461
