### ISSUE TITLE
setAPIUrlStyle defaults to old api style

### ISSUE THREAD

**Issue by maowenbrad** [paultyng/go-unifi#24]
UDM Firmware: 1.8.6
Controller Version: 6.0.43

Currently failing `terraform plan` using provider 0.19.2 with `401 Unauthorized`.

`setAPIUrlStyle` sets the new api style only for 200 responses. The api style check will never set the new api paths for controller versions 6.x.x as the code is effectively unreachable. See below...

``` go
	if resp.StatusCode == http.StatusOk {
		// the new API returns a 200 for a / request
		c.apiPath = apiPathNew
		c.loginPath = loginPathNew
		c.statusPath = statusPathNew
		return nil
	}
```

**Comment by maowenbrad** [comment]
#25

**Comment by paultyng** [comment]
I think this is resolved in v0.22.0 of the provider, let me know if it works for you or not.

**Comment by maowenbrad** [comment]
I'll test and report back.

**Comment by joshuaspence** [comment]
@maowenbrad is this issue resolved?
