### ISSUE TITLE
Setting MGMT functions not exported

### ISSUE THREAD

**Issue by kurtmc** [paultyng/go-unifi#29]
Hey @paultyng is there a reason `getSettingMgmt` and `updateSettingMgmt` functions are not exported?

https://github.com/paultyng/go-unifi/blob/0c90e4c32e223319875ab806ff871650db7beb37/unifi/setting_mgmt.generated.go#L84

Edit: I think I understand now. I will create new exported methods.

**Comment by paultyng** [comment]
You probably figured it out but just for any others coming, I haven't tested all of the generated methods so didn't want to export them until I had a reason to do so (and was able to test them in a consumer).
