### ISSUE TITLE
Add support for management via cloud keys

### ISSUE THREAD

**Issue by paultyng** [paultyng/go-unifi#3]
Did some initial investigation on this, poked around with [MQTT](github.com/eclipse/paho.mqtt.golang)/[WebRTC](github.com/pion/webrtc/v2) packages available in Go. 

The AWS IoT support in the Go SDK does not handle websockets, but you can manually set one up. The AWS SDK presigning adds an expiration I think which messes it up, so you need to create a presign without an expiration: https://gist.github.com/paultyng/d9d3b900b5524d133df2be058148c5c0#file-aws_presign-go

The WebRTC `m=application 9 UDP/DTLS/SCTP webrtc-datachannel` media does not yet seem to be supported in pion/webrtc (specifically the UDP portion). Thats at least my working theory for why this is not working. The above is the media description in the offer/answer in the browser.

**Comment by backkem** [comment]
If you have any questions, the #pion channel of the gopher slack hosts a vibrant community that loves to discuss all things WebRTC.

**Comment by joshuaspence** [comment]
I'm not really sure what this issue is about, closing due to staleness.
